# workflow for running lighthouse audit and see the result
name: Run Lighthouse Audit

on: [pull_request]

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # check node version
          node-version: 12.x
      - name: npm install
        run: |
          yarn
          yarn global add @lhci/cli@0.8.x
      - name: Build the app
        run: |
          yarn build
      - name: Run Lighthouse CI
        run: |
          lhci autorun || echo "Lighthouse CI failed"
        # env:
        #   LHCI_GITHUB_APP_TOKEN:${{LIGHTHOUSE_APP_TOKEN}}